# Generated by Django 3.1.3 on 2020-12-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201206_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_storage', to='blog.blog_storage'),
        ),
    ]
