# Generated by Django 3.1.3 on 2020-12-06 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20201206_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blog_storage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_storage',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_storage', to=settings.AUTH_USER_MODEL),
        ),
    ]
