# Generated by Django 3.1.3 on 2020-12-06 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20201206_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_storage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_storage', to=settings.AUTH_USER_MODEL),
        ),
    ]
